eZ Advanced Autoload: extension\ezadvancedautoload\pv\classes\eZAutoloadGenerator Class Reference
extension\ezadvancedautoload\pv\classes\eZAutoloadGenerator Class Reference
Public Member Functions
__construct (\ezpAutoloadGeneratorOptions $options=null)
Constructs class to generate autoload arrays.
Static Public Member Functions
static findRecursive ($sourceDir, array $includeFilters=array(), array $excludeFilters=array(),\eZAutoloadGenerator $gen)
Walker to find file.
static findRecursiveCallback (\ezpAutoloadFileFindContext $context, $sourceDir, $fileName, $fileInfo)
Callback used ezcBaseFile.
Protected Member Functions
buildFileList ($path, array $extraFilter=null)
Builds a filelist of PHP files in $path.
classExistsInArray ($class, $checkMode, $file, array $inProgressAutoloadArray=null, $generatingMode=null)
Internal method used to check if an class exist autoload arrays.
Static Protected Member Functions
static isFinerFilterEnabled ()
return true if finer filter is enable
Protected Attributes
$activeExtensions
Static Private Member Functions
static getExtensionName ($path)
Return the extension name to the path.
Detailed Description
Definition at line 19 of file ezautoloadgenerator.php.
Constructor & Destructor Documentation
extension\ezadvancedautoload\pv\classes\eZAutoloadGenerator::__construct (\ezpAutoloadGeneratorOptions $ options = null)
Constructs class to generate autoload arrays.
Constructor
Parameters:
ezpAutoloadGeneratorOptions $options
Returns:
void
Definition at line 36 of file ezautoloadgenerator.php.
Member Function Documentation
extension\ezadvancedautoload\pv\classes\eZAutoloadGenerator::buildFileList ($ path, array $ extraFilter = null) [protected]
Builds a filelist of PHP files in $path.
Builds a filelist array of PHP files in $path. Use the static keyword for late static binding
Parameters:
string $path
array $extraFilter
Returns:
array
Definition at line 50 of file ezautoloadgenerator.php.
References extension\ezadvancedautoload\pv\classes\eZAutoloadGenerator\findRecursive().
extension\ezadvancedautoload\pv\classes\eZAutoloadGenerator::classExistsInArray ($ class, $ checkMode, $ file, array $ inProgressAutoloadArray = null, $ generatingMode = null) [protected]
Internal method used to check if an class exist autoload arrays.
Internal method used to check if an class exist autoload arrays. If it already exist then it check the priority with the active extensions.
Parameters:
string $class The name of the class being checked.
int $checkMode The mode whose autoload arrays will be checked.
string $file Filename containing the class.
array $inProgressAutoloadArray The autoload array generated so far.
int $generatingMode The mode we are generating for autoloads for.
Returns:
boolean
Definition at line 159 of file ezautoloadgenerator.php.
References extension\ezadvancedautoload\pv\classes\eZAutoloadGenerator\getExtensionName().
static extension\ezadvancedautoload\pv\classes\eZAutoloadGenerator::findRecursive ($ sourceDir, array $ includeFilters = array(), array $ excludeFilters = array(), \eZAutoloadGenerator $ gen) [static]
Walker to find file.
Uses the walker in ezcBaseFile to find files. This also uses the callback to get progress information about the file search.
Parameters:
string $sourceDir
array $includeFilters
array $excludeFilters
\eZAutoloadGenerator $gen
Returns:
array
Definition at line 81 of file ezautoloadgenerator.php.
Referenced by extension\ezadvancedautoload\pv\classes\eZAutoloadGenerator\buildFileList().
static extension\ezadvancedautoload\pv\classes\eZAutoloadGenerator::findRecursiveCallback (\ezpAutoloadFileFindContext $ context, $ sourceDir, $ fileName, $ fileInfo) [static]
Callback used ezcBaseFile.
Callback function used by eZAutoloadGenerator method
Parameters:
string $ezpAutoloadFileFindContext
string $sourceDir
string $fileName
string $fileInfo
Returns:
void
Definition at line 115 of file ezautoloadgenerator.php.
References extension\ezadvancedautoload\pv\classes\eZAutoloadGenerator\getExtensionName().
static extension\ezadvancedautoload\pv\classes\eZAutoloadGenerator::getExtensionName ($ path) [static, private]
Return the extension name to the path.
Return the name of the ezpublish extension to the path
Parameters:
string $path
Returns:
string
Todo:
put this in a real helper
Definition at line 226 of file ezautoloadgenerator.php.
Referenced by extension\ezadvancedautoload\pv\classes\eZAutoloadGenerator\classExistsInArray(), and extension\ezadvancedautoload\pv\classes\eZAutoloadGenerator\findRecursiveCallback().
static extension\ezadvancedautoload\pv\classes\eZAutoloadGenerator::isFinerFilterEnabled () [static, protected]
return true if finer filter is enable
return true if finer filter is enabled in autoload.ini
Returns:
boolean
Todo:
put this in a real helper
Definition at line 208 of file ezautoloadgenerator.php.
Member Data Documentation
extension::ezadvancedautoload::pv::classes\eZAutoloadGenerator::$activeExtensions [protected]
Definition at line 27 of file ezautoloadgenerator.php.
The documentation for this class was generated from the following file:
D:/git/ezadvancedautoload/private/classes/ezautoloadgenerator.php