eZ Advanced Autoload: extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper Class Reference
extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper Class Reference
Static Public Member Functions
static regenerate ($mode,\eZTemplate $template=null)
static regenerateKernel (\eZTemplate $template=null)
Regenerate autoload for kernel only (ezp_kernel)
static regenerateKernelOverride (\eZTemplate $template=null)
Regenerate autoload for kernel override only (ezp_override)
static regenerateExtension (\eZTemplate $template=null)
Regenerate autoload for extension only (ezp_extension)
static regenerateTest (\eZTemplate $template=null)
Regenerate autoload for tests only (ezp_tests)
Static Private Member Functions
static runGenerate (\ezpAutoloadGeneratorOptions $autoloadOptions,\eZTemplate $template=null)
launch the regeneration
Detailed Description
Definition at line 21 of file templateautoloadgeneratorhelper.php.
Member Function Documentation
static extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper::regenerate ($ mode, \eZTemplate $ template = null) [static]
Definition at line 34 of file templateautoloadgeneratorhelper.php.
References extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper\regenerateExtension(), extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper\regenerateKernel(), extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper\regenerateKernelOverride(), and extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper\regenerateTest().
static extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper::regenerateExtension (\eZTemplate $ template = null) [static]
Regenerate autoload for extension only (ezp_extension)
Regenerate autoload for extension only (ezp_extension)
Parameters:
\eZTemplate $template the template to set the debug if we are in graphical mode
Returns:
void
Definition at line 103 of file templateautoloadgeneratorhelper.php.
References $autoloadOptions, and extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper\runGenerate().
Referenced by extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper\regenerate().
static extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper::regenerateKernel (\eZTemplate $ template = null) [static]
Regenerate autoload for kernel only (ezp_kernel)
Regenerate autoload for kernel only (ezp_kernel)
Parameters:
\eZTemplate $template the template to set the debug if we are in graphical mode
Returns:
void
Definition at line 69 of file templateautoloadgeneratorhelper.php.
References $autoloadOptions, and extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper\runGenerate().
Referenced by extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper\regenerate().
static extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper::regenerateKernelOverride (\eZTemplate $ template = null) [static]
Regenerate autoload for kernel override only (ezp_override)
Regenerate autoload for kernel override only (ezp_override)
Parameters:
\eZTemplate $template the template to set the debug if we are in graphical mode
Returns:
void
Definition at line 86 of file templateautoloadgeneratorhelper.php.
References $autoloadOptions, and extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper\runGenerate().
Referenced by extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper\regenerate().
static extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper::regenerateTest (\eZTemplate $ template = null) [static]
Regenerate autoload for tests only (ezp_tests)
Regenerate autoload for tests only (ezp_tests)
Parameters:
\eZTemplate $template the template to set the debug if we are in graphical mode
Returns:
void
Definition at line 120 of file templateautoloadgeneratorhelper.php.
References $autoloadOptions, and extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper\runGenerate().
Referenced by extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper\regenerate().
static extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper::runGenerate (\ezpAutoloadGeneratorOptions $ autoloadOptions, \eZTemplate $ template = null) [static, private]
launch the regeneration
launch the regeneration
Parameters:
\ezpAutoloadGeneratorOptions $autoloadOptions the options to generate autoload
\eZTemplate $template the template to set the debug if we are in graphical mode
Returns:
void
Definition at line 138 of file templateautoloadgeneratorhelper.php.
References $autoloadGenerator.
Referenced by extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper\regenerateExtension(), extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper\regenerateKernel(), extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper\regenerateKernelOverride(), and extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper\regenerateTest().
The documentation for this class was generated from the following file:
D:/git/ezadvancedautoload/classes/helpers/templateautoloadgeneratorhelper.php