eZ Advanced Autoload: C:/Users/aloyant/ezadvancedautoload/bin/php/ezpgenerateautoloads.php File Reference
C:/Users/aloyant/ezadvancedautoload/bin/php/ezpgenerateautoloads.php File Reference
Variables
if(file_exists('config.php')) $useBundledComponents = defined('EZP_USE_BUNDLED_COMPONENTS') ? EZP_USE_BUNDLED_COMPONENTS === true : file_exists('lib/ezc')
$params = new ezcConsoleInput()
$helpOption = new ezcConsoleOption('h', 'help')
$helpOption mandatory = false
$helpOption shorthelp = 'Show help information'
$targetOption = new ezcConsoleOption('t', 'target', ezcConsoleInput::TYPE_STRING)
$verboseOption = new ezcConsoleOption('v', 'verbose', ezcConsoleInput::TYPE_NONE)
$dryrunOption = new ezcConsoleOption('n', 'dry-run', ezcConsoleInput::TYPE_NONE)
$kernelFilesOption = new ezcConsoleOption('k', 'kernel', ezcConsoleInput::TYPE_NONE)
$kernelOverrideOption = new ezcConsoleOption('o', 'kernel-override', ezcConsoleInput::TYPE_NONE)
$extensionFilesOption = new ezcConsoleOption('e', 'extension', ezcConsoleInput::TYPE_NONE)
$testFilesOption = new ezcConsoleOption('s', 'tests', ezcConsoleInput::TYPE_NONE)
$excludeDirsOption = new ezcConsoleOption('', 'exclude', ezcConsoleInput::TYPE_STRING)
$displayProgressOption = new ezcConsoleOption('p', 'progress', ezcConsoleInput::TYPE_NONE)
$params argumentDefinition = new ezcConsoleArguments()
$params argumentDefinition [0] = new ezcConsoleArgument('extension')
$params argumentDefinition[0] default = getcwd()
if($excludeDirsOption->value!==false) $autoloadOptions = new ezpAutoloadGeneratorOptions()
$autoloadOptions basePath = $params->argumentDefinition['extension']->value
$autoloadOptions searchKernelFiles = $kernelFilesOption->value
$autoloadOptions searchKernelOverride = $kernelOverrideOption->value
$autoloadOptions searchExtensionFiles = $extensionFilesOption->value
$autoloadOptions searchTestFiles = $testFilesOption->value
$autoloadOptions writeFiles = !$dryrunOption->value
$autoloadOptions displayProgress = $displayProgressOption->value
if(!empty($targetOption->value))
$autoloadOptions excludeDirs = $excludeDirs
$autoloadGenerator = new \extension\ezadvancedautoload\pv\classes\eZAutoloadGenerator($autoloadOptions)
Variable Documentation
$autoloadGenerator = new \extension\ezadvancedautoload\pv\classes\eZAutoloadGenerator($autoloadOptions)
Definition at line 153 of file ezpgenerateautoloads.php.
Referenced by extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper\runGenerate().
if ($excludeDirsOption->value!==false) $autoloadOptions = new ezpAutoloadGeneratorOptions()
Definition at line 137 of file ezpgenerateautoloads.php.
Referenced by extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper\regenerateExtension(), extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper\regenerateKernel(), extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper\regenerateKernelOverride(), and extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper\regenerateTest().
$displayProgressOption = new ezcConsoleOption('p', 'progress', ezcConsoleInput::TYPE_NONE)
Definition at line 99 of file ezpgenerateautoloads.php.
$dryrunOption = new ezcConsoleOption('n', 'dry-run', ezcConsoleInput::TYPE_NONE)
Definition at line 69 of file ezpgenerateautoloads.php.
$excludeDirsOption = new ezcConsoleOption('', 'exclude', ezcConsoleInput::TYPE_STRING)
Definition at line 94 of file ezpgenerateautoloads.php.
$extensionFilesOption = new ezcConsoleOption('e', 'extension', ezcConsoleInput::TYPE_NONE)
Definition at line 84 of file ezpgenerateautoloads.php.
$helpOption = new ezcConsoleOption('h', 'help')
Definition at line 54 of file ezpgenerateautoloads.php.
$kernelFilesOption = new ezcConsoleOption('k', 'kernel', ezcConsoleInput::TYPE_NONE)
Definition at line 74 of file ezpgenerateautoloads.php.
$kernelOverrideOption = new ezcConsoleOption('o', 'kernel-override', ezcConsoleInput::TYPE_NONE)
Definition at line 79 of file ezpgenerateautoloads.php.
$params = new ezcConsoleInput()
Definition at line 52 of file ezpgenerateautoloads.php.
$targetOption = new ezcConsoleOption('t', 'target', ezcConsoleInput::TYPE_STRING)
Definition at line 59 of file ezpgenerateautoloads.php.
$testFilesOption = new ezcConsoleOption('s', 'tests', ezcConsoleInput::TYPE_NONE)
Definition at line 89 of file ezpgenerateautoloads.php.
if (file_exists('config.php')) $useBundledComponents = defined('EZP_USE_BUNDLED_COMPONENTS') ? EZP_USE_BUNDLED_COMPONENTS === true : file_exists('lib/ezc')
Script replacement in order to regenerate autoload with ezadvancedautoload extension. Script base on ezpgenerateautoloads.php script for eZPublish community version 2012.2
Author:
Adrien Loyant adrie.nosp@m.n.lo.nosp@m.yant@.nosp@m.te-l.nosp@m.aval..nosp@m.fr
Date:
2012-03-01
Version:
1.0.0
Since:
1.0.0
Copyright:
GNU Public License v.2
Definition at line 22 of file ezpgenerateautoloads.php.
$verboseOption = new ezcConsoleOption('v', 'verbose', ezcConsoleInput::TYPE_NONE)
Definition at line 64 of file ezpgenerateautoloads.php.
$params argumentDefinition = new ezcConsoleArguments()
Definition at line 105 of file ezpgenerateautoloads.php.
$params argumentDefinition[0] = new ezcConsoleArgument('extension')
Definition at line 107 of file ezpgenerateautoloads.php.
$autoloadOptions basePath = $params->argumentDefinition['extension']->value
Definition at line 139 of file ezpgenerateautoloads.php.
$params argumentDefinition [0] default = getcwd()
Definition at line 110 of file ezpgenerateautoloads.php.
$autoloadOptions displayProgress = $displayProgressOption->value
Definition at line 145 of file ezpgenerateautoloads.php.
if (!empty($targetOption->value)) $autoloadOptions excludeDirs = $excludeDirs
Definition at line 151 of file ezpgenerateautoloads.php.
$displayProgressOption mandatory = false
Definition at line 55 of file ezpgenerateautoloads.php.
$autoloadOptions searchExtensionFiles = $extensionFilesOption->value
Definition at line 142 of file ezpgenerateautoloads.php.
$autoloadOptions searchKernelFiles = $kernelFilesOption->value
Definition at line 140 of file ezpgenerateautoloads.php.
$autoloadOptions searchKernelOverride = $kernelOverrideOption->value
Definition at line 141 of file ezpgenerateautoloads.php.
$autoloadOptions searchTestFiles = $testFilesOption->value
Definition at line 143 of file ezpgenerateautoloads.php.
$displayProgressOption shorthelp = 'Show help information'
Definition at line 56 of file ezpgenerateautoloads.php.
$autoloadOptions writeFiles = !$dryrunOption->value
Definition at line 144 of file ezpgenerateautoloads.php.