.TH "C:/Users/aloyant/ezadvancedautoload/doc/examples/call_regenerate_helper.php" 3 "Fri Mar 9 2012" "Version 1.0.0-RC" "eZ Advanced Autoload" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/aloyant/ezadvancedautoload/doc/examples/call_regenerate_helper.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$tpl\fP = \\eZTemplate::factory()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$tpl = \\eZTemplate::factory()"

.PP
\fBExamples: \fP
.in +1c
\fB/doc/examples/call_regenerate_helper\&.php\fP\&.
.PP
Definition at line 5 of file call_regenerate_helper\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for eZ Advanced Autoload from the source code\&.
