.TH "extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper" 3 "Fri Mar 9 2012" "Version 1.0.0-RC" "eZ Advanced Autoload" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extension\ezadvancedautoload\classes\helpers\templateAutoloadGeneratorHelper \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBextension\\ezadvancedautoload\\classes\\helpers\\Helper\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBregenerate\fP ($mode,\\eZTemplate $template=null)"
.br
.ti -1c
.RI "static \fBregenerateKernel\fP (\\eZTemplate $template=null)"
.br
.RI "\fIRegenerate autoload for kernel only (ezp_kernel) \fP"
.ti -1c
.RI "static \fBregenerateKernelOverride\fP (\\eZTemplate $template=null)"
.br
.RI "\fIRegenerate autoload for kernel override only (ezp_override) \fP"
.ti -1c
.RI "static \fBregenerateExtension\fP (\\eZTemplate $template=null)"
.br
.RI "\fIRegenerate autoload for extension only (ezp_extension) \fP"
.ti -1c
.RI "static \fBregenerateTest\fP (\\eZTemplate $template=null)"
.br
.RI "\fIRegenerate autoload for tests only (ezp_tests) \fP"
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static \fBrunGenerate\fP (\\ezpAutoloadGeneratorOptions $autoloadOptions,\\eZTemplate $template=null)"
.br
.RI "\fIlaunch the regeneration \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file templateautoloadgeneratorhelper\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBextension\\ezadvancedautoload\\classes\\helpers\\templateAutoloadGeneratorHelper::regenerate\fP ($mode, \\eZTemplate $template = \fCnull\fP)\fC [static]\fP"

.PP
Definition at line 34 of file templateautoloadgeneratorhelper\&.php\&.
.SS "static \fBextension\\ezadvancedautoload\\classes\\helpers\\templateAutoloadGeneratorHelper::regenerateExtension\fP (\\eZTemplate $template = \fCnull\fP)\fC [static]\fP"

.PP
Regenerate autoload for extension only (ezp_extension) Regenerate autoload for extension only (ezp_extension)
.PP
\fBParameters:\fP
.RS 4
\fI$template\fP the template to set the debug if we are in graphical mode 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 103 of file templateautoloadgeneratorhelper\&.php\&.
.PP
References $autoloadOptions\&.
.SS "static \fBextension\\ezadvancedautoload\\classes\\helpers\\templateAutoloadGeneratorHelper::regenerateKernel\fP (\\eZTemplate $template = \fCnull\fP)\fC [static]\fP"

.PP
Regenerate autoload for kernel only (ezp_kernel) Regenerate autoload for kernel only (ezp_kernel)
.PP
\fBParameters:\fP
.RS 4
\fI$template\fP the template to set the debug if we are in graphical mode 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 69 of file templateautoloadgeneratorhelper\&.php\&.
.PP
References $autoloadOptions\&.
.SS "static \fBextension\\ezadvancedautoload\\classes\\helpers\\templateAutoloadGeneratorHelper::regenerateKernelOverride\fP (\\eZTemplate $template = \fCnull\fP)\fC [static]\fP"

.PP
Regenerate autoload for kernel override only (ezp_override) Regenerate autoload for kernel override only (ezp_override)
.PP
\fBParameters:\fP
.RS 4
\fI$template\fP the template to set the debug if we are in graphical mode 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 86 of file templateautoloadgeneratorhelper\&.php\&.
.PP
References $autoloadOptions\&.
.SS "static \fBextension\\ezadvancedautoload\\classes\\helpers\\templateAutoloadGeneratorHelper::regenerateTest\fP (\\eZTemplate $template = \fCnull\fP)\fC [static]\fP"

.PP
Regenerate autoload for tests only (ezp_tests) Regenerate autoload for tests only (ezp_tests)
.PP
\fBParameters:\fP
.RS 4
\fI$template\fP the template to set the debug if we are in graphical mode 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 120 of file templateautoloadgeneratorhelper\&.php\&.
.PP
References $autoloadOptions\&.
.SS "static \fBextension\\ezadvancedautoload\\classes\\helpers\\templateAutoloadGeneratorHelper::runGenerate\fP (\\ezpAutoloadGeneratorOptions $autoloadOptions, \\eZTemplate $template = \fCnull\fP)\fC [static, private]\fP"

.PP
launch the regeneration launch the regeneration
.PP
\fBParameters:\fP
.RS 4
\fI$autoloadOptions\fP the options to generate autoload 
.br
\fI$template\fP the template to set the debug if we are in graphical mode 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 138 of file templateautoloadgeneratorhelper\&.php\&.
.PP
References $autoloadGenerator\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for eZ Advanced Autoload from the source code\&.
