.TH "extension\ezadvancedautoload\classes\enums\autoloadGeneratorEnum" 3 "Thu Mar 8 2012" "Version 1.0.0-RC" "eZ Advanced Autoload" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extension\ezadvancedautoload\classes\enums\autoloadGeneratorEnum \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fB__default\fP = self::EXTENSION"
.br
.ti -1c
.RI "const \fBKERNEL\fP = 1"
.br
.ti -1c
.RI "const \fBKERNEL_OVERRIDE\fP = 2"
.br
.ti -1c
.RI "const \fBEXTENSION\fP = 3"
.br
.ti -1c
.RI "const \fBTEST\fP = 4"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file autoloadgeneratorenum\&.php\&.
.SH "Member Data Documentation"
.PP 
.SS "const extension::ezadvancedautoload::classes::enums\\\fBautoloadGeneratorEnum::__default\fP = self::EXTENSION"
.PP
Definition at line 27 of file autoloadgeneratorenum\&.php\&.
.SS "const extension::ezadvancedautoload::classes::enums\\\fBautoloadGeneratorEnum::EXTENSION\fP = 3"
.PP
Definition at line 50 of file autoloadgeneratorenum\&.php\&.
.SS "const extension::ezadvancedautoload::classes::enums\\\fBautoloadGeneratorEnum::KERNEL\fP = 1"
.PP
Definition at line 35 of file autoloadgeneratorenum\&.php\&.
.SS "const extension::ezadvancedautoload::classes::enums\\\fBautoloadGeneratorEnum::KERNEL_OVERRIDE\fP = 2"
.PP
Definition at line 43 of file autoloadgeneratorenum\&.php\&.
.SS "const extension::ezadvancedautoload::classes::enums\\\fBautoloadGeneratorEnum::TEST\fP = 4"
.PP
Definition at line 57 of file autoloadgeneratorenum\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for eZ Advanced Autoload from the source code\&.
