.TH "extension" 3 "Thu Mar 8 2012" "Version 1.0.0-RC" "eZ Advanced Autoload" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extension \- 
.PP
Enumeration class for autoload generator\&.  

.SH SYNOPSIS
.br
.PP
.SS "Packages"

.in +1c
.ti -1c
.RI "namespace \fBezadvancedautoload\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Enumeration class for autoload generator\&. 

File containing the eZAutoloadGenerator class\&.
.PP
Helper witch provide help to correctly build autoload file\&.
.PP
Meta class for all helpers\&.
.PP
UnexpectedModeException class\&.
.PP
Classe witch define all enumeration use for build autoload This class will need to extends \fCSplEnum\fP soon It's a final class because there is no need to extends it; It should manage all available parameter for autoload generation with eZPublish
.PP
\fBAuthor:\fP
.RS 4
Adrien Loyant <adrien.loyant@te-laval.fr>
.RE
.PP
\fBDate:\fP
.RS 4
2012-03-01 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBCopyright:\fP
.RS 4
GNU Public License v\&.2
.RE
.PP
.PP
UnexpectedModeException class for throwing exception when the mode for autoload generation is not correct
.PP
\fBAuthor:\fP
.RS 4
Adrien Loyant <adrien.loyant@te-laval.fr>
.RE
.PP
\fBDate:\fP
.RS 4
2012-03-01 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBCopyright:\fP
.RS 4
GNU Public License v\&.2
.RE
.PP
.PP
All helper classes should extends this class because this is their MetaClass
.PP
\fBAuthor:\fP
.RS 4
Adrien Loyant <adrien.loyant@te-laval.fr>
.RE
.PP
\fBDate:\fP
.RS 4
2012-03-01 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBCopyright:\fP
.RS 4
GNU Public License v\&.2
.RE
.PP
.PP
Helper witch provide help to correctly build autoload file
.PP
\fBAuthor:\fP
.RS 4
Adrien Loyant <adrien.loyant@te-laval.fr>
.RE
.PP
\fBDate:\fP
.RS 4
2012-03-01 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBCopyright:\fP
.RS 4
GNU Public License v\&.2
.RE
.PP
.PP
This class permits to generate autoload array without considering unactivated extensions
.PP
\fBAuthor:\fP
.RS 4
Adrien Loyant <adrien.loyant@te-laval.fr>
.RE
.PP
\fBDate:\fP
.RS 4
2012-03-01 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBSince:\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBCopyright:\fP
.RS 4
GNU Public License v\&.2
.RE
.PP
\fBSee also:\fP
.RS 4
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for eZ Advanced Autoload from the source code\&.
