.TH "extension\ezadvancedautoload\classes\exceptions\unexpectedModeException" 3 "Fri Mar 9 2012" "Version 1.0.0-RC" "eZ Advanced Autoload" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extension\ezadvancedautoload\classes\exceptions\unexpectedModeException \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($mode=null, $code=null,\\Exception $previous=null)"
.br
.RI "\fI\fBunexpectedModeException\fP constructor \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB$mode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBExamples: \fP
.in +1c
\fB/doc/examples/call_regenerate_helper\&.php\fP\&.
.PP
Definition at line 17 of file unexpectedmodeexception\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBextension\\ezadvancedautoload\\classes\\exceptions\\unexpectedModeException::__construct\fP ($mode = \fCnull\fP, $code = \fCnull\fP, \\Exception $previous = \fCnull\fP)"

.PP
\fBunexpectedModeException\fP constructor \fBunexpectedModeException\fP constructor
.PP
\fBParameters:\fP
.RS 4
\fI$mode\fP 
.br
\fI$code\fP 
.br
\fI$previous\fP 
.RE
.PP

.PP
Definition at line 35 of file unexpectedmodeexception\&.php\&.
.SH "Field Documentation"
.PP 
.SS "\fBextension\\ezadvancedautoload\\classes\\exceptions\\unexpectedModeException::$mode\fP\fC [private]\fP"

.PP
Definition at line 25 of file unexpectedmodeexception\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for eZ Advanced Autoload from the source code\&.
