.TH "extension\ezadvancedautoload\classes\helpers\Helper" 3 "Thu Mar 8 2012" "Version 1.0.0-RC" "eZ Advanced Autoload" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extension\ezadvancedautoload\classes\helpers\Helper \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBextension\\ezadvancedautoload\\classes\\helpers\\templateAutoloadGeneratorHelper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.RI "\fIThere are no constructors for an abstract class\&. \fP"
.ti -1c
.RI "\fB__clone\fP ()"
.br
.RI "\fIAn helper isn't clonable\&. \fP"
.ti -1c
.RI "\fB__sleep\fP ()"
.br
.RI "\fIAn helper isn't serializable\&. \fP"
.ti -1c
.RI "\fB__wakeup\fP ()"
.br
.RI "\fIAn helper isn't serializable\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file helper\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "extension\\ezadvancedautoload\\classes\\helpers\\\fBHelper::__construct\fP ()\fC [final]\fP"
.PP
There are no constructors for an abstract class\&. There are no constructors for an abstract class
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 25 of file helper\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "extension\\ezadvancedautoload\\classes\\helpers\\\fBHelper::__clone\fP ()\fC [final]\fP"
.PP
An helper isn't clonable\&. An helper isn't clonable
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 35 of file helper\&.php\&.
.SS "extension\\ezadvancedautoload\\classes\\helpers\\\fBHelper::__sleep\fP ()\fC [final]\fP"
.PP
An helper isn't serializable\&. An helper isn't serializable
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 45 of file helper\&.php\&.
.SS "extension\\ezadvancedautoload\\classes\\helpers\\\fBHelper::__wakeup\fP ()\fC [final]\fP"
.PP
An helper isn't serializable\&. An helper isn't serializable
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 55 of file helper\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for eZ Advanced Autoload from the source code\&.
