.TH "extension\ezadvancedautoload\classes\exceptions\unexpectedModeException" 3 "Thu Mar 8 2012" "Version 1.0.0-RC" "eZ Advanced Autoload" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extension\ezadvancedautoload\classes\exceptions\unexpectedModeException \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($mode=null, $code=null,\\Exception $previous=null)"
.br
.RI "\fI\fBunexpectedModeException\fP constructor \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB$mode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file unexpectedmodeexception\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "extension\\ezadvancedautoload\\classes\\exceptions\\\fBunexpectedModeException::__construct\fP ($mode = \fCnull\fP, $code = \fCnull\fP, \\Exception $previous = \fCnull\fP)"
.PP
\fBunexpectedModeException\fP constructor \fBunexpectedModeException\fP constructor
.PP
\fBParameters:\fP
.RS 4
\fI$mode\fP 
.br
\fI$code\fP 
.br
\fI\\Exception\fP $previous 
.RE
.PP

.PP
Definition at line 35 of file unexpectedmodeexception\&.php\&.
.PP
References extension\\ezadvancedautoload\\classes\\exceptions\\unexpectedModeException\\$mode\&.
.SH "Member Data Documentation"
.PP 
.SS "extension::ezadvancedautoload::classes::exceptions\\unexpectedModeException::$mode\fC [private]\fP"
.PP
Definition at line 25 of file unexpectedmodeexception\&.php\&.
.PP
Referenced by extension\\ezadvancedautoload\\classes\\exceptions\\unexpectedModeException\\__construct()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for eZ Advanced Autoload from the source code\&.
