.TH "todo" 3 "Fri Mar 9 2012" "Version 1.0.0-RC" "eZ Advanced Autoload" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
.IP "\fBGlobal \fBextension::getExtensionName\fP ($path)\fP" 1c
put this in a real helper  
.IP "\fBGlobal \fBextension::isFinerFilterEnabled\fP ()\fP" 1c
put this in a real helper 
.PP

